import React, { useState } from 'react';
import api from '../../services/api';
import icons from '../../components/Icons';
import Toast from '../../components/Toast';

const AiTimetableGenerator = () => {
    const [loading, setLoading] = useState(false);
    const [saving, setSaving] = useState(false);
    const [generatedData, setGeneratedData] = useState(null);
    const [toast, setToast] = useState(null);
    const [formData, setFormData] = useState({
        branch: 'CSE',
        semester: 3,
        section: 'A',
        subjects: 'DBMS, OS, CN, SE',
        slotsPerDay: 4,
        startTime: '09:00',
        endTime: '13:00'
    });

    const handleChange = (e) => {
        const { name, value } = e.target;
        setFormData(prev => ({ ...prev, [name]: value }));
    };

    const handleGenerate = async (e) => {
        e.preventDefault();
        setLoading(true);
        setGeneratedData(null);

        try {
            const payload = {
                ...formData,
                semester: parseInt(formData.semester),
                slotsPerDay: parseInt(formData.slotsPerDay),
                subjects: formData.subjects.split(',').map(s => s.trim()).filter(s => s !== '')
            };

            const response = await api.post('/ai/generate-timetable', payload);
            if (response.data.status === 'success') {
                setGeneratedData(response.data);
                setToast({ message: 'Timetable generated by AI!', type: 'success' });
            } else {
                setToast({ message: 'Failed to generate timetable.', type: 'error' });
            }
        } catch (error) {
            console.error('AI Generation Error:', error);
            setToast({ message: error.response?.data?.message || 'Error communicating with AI', type: 'error' });
        } finally {
            setLoading(false);
        }
    };

    const handleSave = async () => {
        if (!generatedData) return;
        setSaving(true);

        try {
            const response = await api.post('/timetables/save-ai', generatedData);
            if (response.data.success) {
                setToast({ message: 'Timetable saved to database!', type: 'success' });
                setGeneratedData(null); // Clear preview after save
            }
        } catch (error) {
            console.error('Save Error:', error);
            setToast({ message: 'Failed to save timetable.', type: 'error' });
        } finally {
            setSaving(false);
        }
    };

    return (
        <>
            <div className="toast-container">
                {toast && <Toast message={toast.message} type={toast.type} onClose={() => setToast(null)} />}
            </div>
            <header className="top-header">
                <div>
                    <h1 className="page-title">AI Timetable Generator</h1>
                    <p style={{ color: 'var(--text-muted)', fontSize: '0.85rem' }}>Use Grok AI to create optimized weekly schedules instantly.</p>
                </div>
                <div className="header-actions">
                    <div className="header-icon" style={{ background: 'var(--bg-elevated)', padding: '10px', borderRadius: '50%', color: 'var(--primary-400)' }}>
                        {icons.sparkles}
                    </div>
                </div>
            </header>

            <div className="page-content animate-fade-in">
                <div style={{ display: 'grid', gridTemplateColumns: generatedData ? '350px 1fr' : '1fr', gap: '24px', alignItems: 'start' }}>
                    
                    {/* Input Section */}
                    <section className="card" style={{ padding: '24px' }}>
                        <h3 style={{ marginBottom: '20px', fontSize: '1.1rem' }}>Configuration</h3>
                        <form onSubmit={handleGenerate}>
                            <div className="form-group">
                                <label className="form-label">Branch</label>
                                <input
                                    className="form-input"
                                    name="branch"
                                    value={formData.branch}
                                    onChange={handleChange}
                                    placeholder="e.g. CSE, ME, ECE"
                                    required
                                />
                            </div>
                            <div style={{ display: 'flex', gap: '16px' }}>
                                <div className="form-group" style={{ flex: 1 }}>
                                    <label className="form-label">Semester</label>
                                    <input
                                        className="form-input"
                                        type="number"
                                        name="semester"
                                        value={formData.semester}
                                        onChange={handleChange}
                                        min="1" max="8"
                                        required
                                    />
                                </div>
                                <div className="form-group" style={{ flex: 1 }}>
                                    <label className="form-label">Section</label>
                                    <input
                                        className="form-input"
                                        name="section"
                                        value={formData.section}
                                        onChange={handleChange}
                                        placeholder="A, B, C"
                                        required
                                    />
                                </div>
                            </div>
                            <div className="form-group">
                                <label className="form-label">Subjects (Comma separated)</label>
                                <textarea
                                    className="form-input"
                                    name="subjects"
                                    value={formData.subjects}
                                    onChange={handleChange}
                                    placeholder="DBMS, Operating Systems, Computer Networks..."
                                    rows="3"
                                    style={{ resize: 'none' }}
                                    required
                                />
                            </div>
                            <div style={{ display: 'flex', gap: '16px' }}>
                                <div className="form-group" style={{ flex: 1 }}>
                                    <label className="form-label">Slots/Day</label>
                                    <input
                                        className="form-input"
                                        type="number"
                                        name="slotsPerDay"
                                        value={formData.slotsPerDay}
                                        onChange={handleChange}
                                        min="1" max="8"
                                        required
                                    />
                                </div>
                                <div className="form-group" style={{ flex: 1 }}>
                                    <label className="form-label">Start Time</label>
                                    <input
                                        className="form-input"
                                        type="time"
                                        name="startTime"
                                        value={formData.startTime}
                                        onChange={handleChange}
                                        required
                                    />
                                </div>
                            </div>
                            <button type="submit" className="btn btn-primary" style={{ width: '100%', marginTop: '10px' }} disabled={loading}>
                                {loading ? 'AI is thinking...' : 'Generate with AI'}
                            </button>
                        </form>
                    </section>

                    {/* Preview Section */}
                    {generatedData ? (
                        <section className="card animate-slide-up" style={{ padding: 0, overflow: 'hidden' }}>
                            <div style={{ 
                                padding: '20px 24px', 
                                borderBottom: '1px solid var(--border-subtle)',
                                display: 'flex', 
                                justifyContent: 'space-between', 
                                alignItems: 'center',
                                background: 'var(--bg-elevated)'
                            }}>
                                <div>
                                    <h3 style={{ fontSize: '1.1rem' }}>AI Generated Preview</h3>
                                    <p style={{ fontSize: '0.75rem', color: 'var(--text-muted)' }}>
                                        {generatedData.batch.branch} Sem {generatedData.batch.semester} ({generatedData.batch.section})
                                    </p>
                                </div>
                                <div style={{ display: 'flex', gap: '12px' }}>
                                    <button className="btn btn-secondary" onClick={() => setGeneratedData(null)}>Discard</button>
                                    <button className="btn btn-primary" style={{ background: 'var(--accent-emerald)', borderColor: 'var(--accent-emerald)' }} onClick={handleSave} disabled={saving}>
                                        {saving ? 'Saving...' : 'Approve & Save'}
                                    </button>
                                </div>
                            </div>

                            <div style={{ maxHeight: '600px', overflowY: 'auto' }}>
                                <table className="table">
                                    <thead>
                                        <tr>
                                            <th>Day</th>
                                            <th>Time Slot</th>
                                            <th>Subject Name</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {generatedData.slots.map((slot, i) => (
                                            <tr key={i}>
                                                <td style={{ fontWeight: 700, color: 'var(--primary-400)' }}>{slot.day}</td>
                                                <td style={{ fontSize: '0.85rem' }}>{slot.startTime} - {slot.endTime}</td>
                                                <td style={{ fontWeight: 500 }}>{slot.subject}</td>
                                            </tr>
                                        ))}
                                    </tbody>
                                </table>
                            </div>
                        </section>
                    ) : (
                        <div style={{ 
                            height: '100%', 
                            display: 'flex', 
                            flexDirection: 'column', 
                            alignItems: 'center', 
                            justifyContent: 'center',
                            padding: '60px',
                            color: 'var(--text-muted)',
                            background: 'rgba(255,255,255,0.02)',
                            borderRadius: 'var(--radius-lg)',
                            border: '1px dashed var(--border-subtle)'
                        }}>
                            <div style={{ fontSize: '3rem', marginBottom: '20px', opacity: 0.5 }}>🤖</div>
                            <p>Fill the configuration to generate a timetable preview.</p>
                        </div>
                    )}
                </div>
            </div>
        </>
    );
};

export default AiTimetableGenerator;
